"""reservation added

Revision ID: 6bab90395811
Revises: ce6e3207343e
Create Date: 2023-04-25 19:59:18.187015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bab90395811'
down_revision = 'ce6e3207343e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('type_of_room', sa.String(length=100), nullable=False),
    sa.Column('Bedding_Type', sa.String(length=100), nullable=False),
    sa.Column('Number_of_rooms', sa.String(length=100), nullable=False),
    sa.Column('check_in', sa.String(length=100), nullable=False),
    sa.Column('check_out', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
