"""accept/delete added

Revision ID: 72ad1395da87
Revises: 6bab90395811
Create Date: 2023-04-25 20:14:44.948180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ad1395da87'
down_revision = '6bab90395811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accepted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('type_of_room', sa.String(length=100), nullable=False),
    sa.Column('bedding', sa.String(length=100), nullable=False),
    sa.Column('number_of_room', sa.String(length=100), nullable=False),
    sa.Column('check_in', sa.String(length=100), nullable=False),
    sa.Column('check_out', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('type_of_room', sa.String(length=100), nullable=False),
    sa.Column('bedding', sa.String(length=100), nullable=False),
    sa.Column('number_of_room', sa.String(length=100), nullable=False),
    sa.Column('check_in', sa.String(length=100), nullable=False),
    sa.Column('check_out', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reject')
    op.drop_table('accepted')
    # ### end Alembic commands ###
